### ISSUE TITLE
Forge 1.19.2 Mod Loading failed "requires arc 1.0 or above" Architectury API already installed

### ISSUE THREAD

**Issue by Mnesikos** [DAQEM/JobsPlusRemastered#13]
Instance won't load due to jobsplus and itemrestrictions requiring arc. If arc is meant to be architectury api (that's what curseforge points to), it is already installed.

Versions:
- forge 43.4.0
- jobsplus (remastered) 1.0
- itemrestrictions 1.0
- architectury 6.6.92

[mclo.gs crash report](https://mclo.gs/x8IK8gd)

![2024-08-29_18 54 40](https://github.com/user-attachments/assets/791b11c8-c4da-4a68-a520-c778d126e4d0)

**Comment by DAQEM** [comment]
This is [Arc](https://www.curseforge.com/minecraft/mc-mods/arc) 😉
