### ISSUE TITLE
No Job EXP after Death

### ISSUE THREAD

**Issue by TrustiDx** [DAQEM/JobsPlusRemastered#2]
Hi!

I have the following problem, as soon as I die I no longer get experience for jobs.
If I restart the world (same on server) it works again.. until i die.
I use the standard professions, no customized data packs.

Mod List + Versions:
Minecraft: 1.20.1
Forge: 47.2.20
SuperMartijn642 Config Lib: 1.1.8
Architectury: 9.1.13
Ui Lib: 0.2.12
Arc: 1.4.1
ItemRestrictions: 1.1.2
Jobs+: 1.3

**Comment by AJM10565** [comment]
I also have this issue. I'm playing the MineColonies Croptoria - Season 2 with default configs.

**Comment by DAQEM** [comment]
This issue has been fixed by commit DAQEM/ArcLib@46089b4d6d99a04069fd2e4f4b8c369974de7b4d.
