### ISSUE TITLE
1.20.1 Crash on startup 1.3.3

### ISSUE THREAD

**Issue by xd4rkzghost01** [DAQEM/JobsPlusRemastered#4]
Hi There! i get an issue with the mod last day:
Minecraft crash upon startup. Can't get trought the red loading screen.

Version:
Minecraft **1.20.1**
Forge **47.2.18**
Optifine **1.20.1 HD6**
JobsPlus Remastered **1.3.3**
And **_139_** other mods

Latest Log with your update
[Latest Log](https://github.com/DAQEM/JobsPlusRemastered/files/14470754/latest.log)

Going back to JPR 1.3.2 works perfectly fine. Can you take a look ? I love this mod and want it in the modpack i play.

**Comment by LeoDemitori** [comment]
same problem on **fabric 1.20.1**

**Comment by DAQEM** [comment]
Fixed in 1.3.4
